services:
  web-express-ts:
    build:
      dockerfile: ./web-express-ts.dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - MONGO_USER=root
      - MONGO_PASSWORD=example
      - MONGO_DB=todo-app
      - MONGO_DOMAIN=mongo
      - MONGO_PORT=27017
      - MONGO_AUTH_DB=admin
    depends_on:
      - mongo
    develop:
      watch:
        - action: sync
          path: ./web/express-ts/dist
          target: /todo-app/web/express-ts/dist
        - action: rebuild
          path: ./package.json
        - action: sync
          path: ./lib/interfaces/dist
          target: /todo-app/lib/interfaces/dist
        - action: sync
          path: ./lib/repositories/dist
          target: /todo-app/lib/repositories/dist
        - action: sync
          path: ./lib/services/dist
          target: /todo-app/lib/services/dist

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_BASICAUTH: false
